console.log("234a");
console.log('1'+ 2 + 2);
let apples="2";
let oranges="3";
console.log( +apples + +oranges);
let counter=1;
console.log(2 * ++counter);
console.log(undefined == null);
console.log(undefined === null);
console.log(null == "\n0\n");
console.log(null === +"\n0\n");